config/routes.rb
Footprint::Application.routes.draw do



  get '/auth/:provider/callback', to: 'users#oauth'
  post '/auth/:provider/callback', to: 'users#oauth'

  # resources :oauth, only: [:index]

  # resources :sessions, only: [:create]
  # get "/printheader" => "controller#action"

  # root :to => 'welcome#index'

  root :to => 'users#index'

  match 'login' => 'sessions#new', :as => "login"

  resources :users, :only => [:show, :index, :new, :create] do
    member do
      post 'oauth'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id               :integer          not null, primary key
#  meters_driven    :integer
#  user_id          :integer
#  score            :integer
#  meters_walked    :integer
#  meters_biked     :integer
#  carbon_footprint :integer
#  calories         :integer
#

class Event < ActiveRecord::Base
	attr_accessible :meters_driven, :user_id, :score, :meters_walked, :meters_biked, :carbon_footprint, :calories
	belongs_to :user

	# after_save :update_user_score

	private
	def update_user_score
		self.user.update_score!
	end
end

app/models/friendship.rb
# == Schema Information
#
# Table name: friendships
#
#  id        :integer          not null, primary key
#  user_id   :integer
#  friend_id :integer
#

class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: "User"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  email               :string(255)
#  zipcode             :integer
#  score               :integer
#  moves_access_token  :string(255)
#  moves_refresh_token :string(255)
#  password_digest     :string(255)
#

class User < ActiveRecord::Base
	attr_accessible :name, :email, :zipcode, :score, :password, :password_confirmation, :password_digest

	validates :name, :email, :zipcode, presence: true
	validates :zipcode, length: {is: 5}

	has_many :friendships
	has_many :friends, through: :friendships
	# validates :name, :email, :zipcode, presence: true
	# validates :zipcode, length: {is: 5}
	has_many :events
  has_secure_password

  def update_score!
  	all_events = self.events.all
  	all_events.map! { |event| event = event.score }
  	total = all_events.reduce(:+)
  	self.score = total / all_events.size
  	self.save
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user=(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  helper_method :current_user, :logged_in?, :current_user=
end

app/controllers/oauth_controller.rb
class OauthsController < ApplicationController
	def index
		p "*" * 100
		p request.env['omniauth.auth']
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:user][:email])
    user = @user.authenticate(params[:user][:password])
    if user
      self.current_user = user
      redirect_to root_path
    else
      flash.now.alert = "Invalid username or password"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UserHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.save
    if @user.errors.any?
      flash.now[:signup_errors] = @user.errors.full_messages
      render new_user_path
    else
      self.current_user = @user
      redirect_to root_path
    end
  end

  def oauth
    user = self.current_user
    user.moves_access_token = auth_hash[:credentials][:token]
    user.moves_refresh_token = auth_hash[:credentials][:refresh_token]
    user.save
    redirect_to users_path
  end

  def auth_hash
    request.env['omniauth.auth']
  end
    
  def index
    if !self.current_user
      redirect_to login_path
    else
      @user = self.current_user
      @top_users = User.order('score DESC').limit(5)

      #going to moves api
      daily_log = moves_daily_log(@user)
      daily_walk = daily_walk_distance(daily_log)
      daily_cycle = daily_cycle_distance(daily_log)
      daily_trip = daily_trip_distance(daily_log)

      daily_CO2_footprint = berkeley_calc(daily_trip)

      # writing event to db
      @user.events << Event.create(meters_driven: daily_trip, meters_walked: daily_walk, meters_biked: daily_cycle, carbon_footprint: daily_CO2_footprint)
      @daily_events = @user.events.last
    end
  end

  def show
    @user = self.current_user
    render layout: false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendship_helper.rb
module FriendshipHelper
	def search_for_friends(fb_data)
		#TODO : Do when we know what facebook gives us
	end

	def add_friend(email)
		current_user.friendships.create(friend_id: User.find_by_email(email).id)
	end
end

app/helpers/gravatar_helper.rb
module GravatarHelper
  def gravatar(user, size)
    email_digest = Digest::MD5.hexdigest("#{user.email}")
    "https://secure.gravatar.com/avatar/#{email_digest}?s=#{size}"
  end
end

app/helpers/user_helper.rb
module UserHelper

  ########################
  def berkeley_calc(meters, mpg="24")
    yearly_miles = meters_to_miles(meters) * 365

    response = HTTParty.get("https://apis-dev.berkeley.edu/coolclimate/footprint-sandbox?input_location=20151&input_income=1&input_location_mode=1&input_size=0&input_footprint_transportation_miles1=#{yearly_miles}&input_footprint_transportation_mpg1=#{mpg}&input_footprint_transportation_fuel1=0&app_id=f5e89990&app_key=d1847181c85aa26015b4ae9afb230b91")
  
    # response.code, response.message, response.headers.inspect
    parsed_response = Crack::XML.parse(response.body)

    # Berkeley API returns tons of CO2/year
    carbon_tons_by_year = parsed_response["response"]["result_motor_vehicles_direct"].to_f + parsed_response["response"]["result_motor_vehicles_indirect"].to_f
    
    # Convert to lbs of CO2/Day
    carbon_tons_by_day = carbon_tons_by_year / 365

    # Daily lbs of CO2/day
    carbon_lbs_by_day = carbon_tons_by_day * 2204.6
  end

  def moves_daily_log(user)
    access_token = user.moves_access_token
    response = HTTParty.get("https://api.moves-app.com/api/v1/user/activities/daily/20130809?access_token=#{access_token}")
    daily_log = JSON.parse(response.body)
  end

  def daily_walk_distance(daily_log)
    @daily_walk_distance = 0

    daily_log[0]['segments'].each do |segment|
      segment['activities'].each do |activity|
        @daily_walk_distance += activity['distance'] if activity['activity'] == 'wlk' 
      end
    end

    @daily_walk_distance
  end

  def daily_trip_distance(daily_log)
    @daily_trip_distance = 0

    daily_log[0]['segments'].each do |segment|
      segment['activities'].each do |activity|
        @daily_trip_distance += activity['distance'] if activity['activity'] == 'trp' 
      end
    end

    @daily_trip_distance
  end

  def daily_cycle_distance(daily_log)
    @daily_cycle_distance = 0

    daily_log[0]['segments'].each do |segment|
      segment['activities'].each do |activity|
        @daily_cycle_distance += activity['distance'] if activity['activity'] == 'cyc' 
      end
    end

    @daily_cycle_distance
  end

  private
  def meters_to_miles(meters=0)
    meters * 0.00062137
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Footprint
    = stylesheet_link_tag    "bootstrap", :media => "all"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %nav
      %ul.left
        / .button_link
        %li= button_to "footprint", root_path, class: "nav_button bg-white"
        -if current_user
          %li= link_to image_tag(gravatar(@user,50)), user_path(@user)
          %li=button_to "Authorize with Moves", '/auth/moves', class: "nav_button bg-white"
          %li= link_to image_tag( 'moves_logo.png', size: '50x50'), 'auth/moves'
      %ul.right
        -if current_user
          %li=button_to "Logout", session_path(@user.object_id), :method=>:delete, class: "nav_button bg-blue"

    .container
      = yield

app/views/users/index.html.haml
#daily-score
  %h1 7.5
  %p Pounds CO2/day

#dashboard
  #activity
    %ul
      %h2=@daily_events.meters_walked
      %p meters walked 
      %h2=@daily_events.meters_biked
      %p meters biked
      %h2=@daily_events.meters_driven
      %p meters driven
      %h2=@daily_events.carbon_footprint
      %p lbs of CO2 emissions

  #rankings
    %h2 Footprint Rankings
    %ul
      - @top_users.each_with_index do |user, index|
        %li= link_to "<img src='#{gravatar(user,75)}' alt='#{user.name}'> #{index + 1} #{user.name}".html_safe, user_path(user), class: 'user_profile', data: {id: user.id }
/ Modal
#myModal.modal.fade
  .modal-dialog
    .modal-content
      .modal-body
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/users/new.html.haml
#login-box
  %h2 Welcome to Footprints
  %p Join us in helping measure and compare your carbon footprint as you move around!
  %p=link_to "Already have an account?", new_session_path
  =form_for @user, {url: sessions_path } do |f|
    =f.text_field :name, {class: "login-input", placeholder: "NAME"}
    =f.email_field :email, {class: "login-input", placeholder: "EMAIL"}
    =f.text_field :zipcode, {class: "login-input", placeholder: "ZIPCODE"}
    =f.password_field :password, {class: "login-input", placeholder: "PASSWORD"}
    =f.submit "Sign Up", class: "login-button"
  - if flash[:signup_errors]
    - flash[:signup_errors].each do |error|
      %p= error

app/views/users/show.html.haml
#user-info
  %img{src: "#{gravatar(@user,50)}"}
  %h3= "#{@user.name}"